# config used for "predict_library" and "first search" steps
# (Default settings are suitable for the first search, except the multi-step search which has to be deactivated)
general:
  mbr_step_enabled: false # do not change for "first search"

# Add remaining config settings per your use case ...
