name: PeptideCentric.v1
general:
  thread_count: 10
  reuse_calibration: false
  reuse_quant: false
  use_gpu: false
  astral_ms1: false
  log_level: INFO
library_prediction:
  predict: false
  enzyme: trypsin
  fixed_modifications: Carbamidomethyl@C
  variable_modifications: Oxidation@M;Acetyl@Protein N-term
  max_var_mod_num: 1
  missed_cleavages: 1
  precursor_len:
    - 7
    - 35
  precursor_charge:
    - 2
    - 4
  precursor_mz:
    - 400
    - 1200
  fragment_mz:
    - 200
    - 2000
  fragment_types: b;y
  max_fragment_charge: 2
  nce: 25
  instrument: Fusion
search:
  channel_filter: ''
  exclude_shared_ions: true
  compete_for_fragments: true
  target_num_candidates: 2
  target_ms1_tolerance: 5
  target_ms2_tolerance: 10
  target_mobility_tolerance: 0.04
  target_rt_tolerance: 100
  quant_window: 3
  quant_all: false
fdr:
  fdr: 0.01
  group_level: proteins
  inference_strategy: library
  competetive_scoring: true
  channel_wise_fdr: false
  keep_decoys: false
search_initial:
  initial_num_candidates: 5
  initial_ms1_tolerance: 10
  initial_ms2_tolerance: 10
  initial_mobility_tolerance: 0.08
  initial_rt_tolerance: 100
multiplexing:
  multiplexed_quant: false
  target_channels: 4,8
  decoy_channel: 12
  reference_channel: 0
  competetive_scoring: true
search_output:
  min_k_fragments: 12
  min_correlation: 0.9
  num_samples_quadratic: 50
  min_nonnan: 3
  normalize_lfq: true
  peptide_level_lfq: false
  precursor_level_lfq: false
