name: PeptideCentric.v1
general:
  thread_count: 10
  reuse_calibration: true
  reuse_quant: false
  save_figures: false
  mmap_detector_events: false
  astral_ms1: false
library_loading:
  channel_filter: ''
  exclude_shared_ions: true
extraction_target:
  target_num_candidates: 5
  target_ms1_tolerance: 15
  target_ms2_tolerance: 15
  target_mobility_tolerance: 0.04
  target_rt_tolerance: 30
fdr:
  fdr: 0.01
  competetive_scoring: true
  channel_wise_fdr: false
  keep_decoys: false
extraction_initial:
  initial_num_candidates: 2
  initial_ms1_tolerance: 30
  initial_ms2_tolerance: 30
  initial_mobility_tolerance: 0.08
  initial_rt_tolerance: 240
multiplexing:
  multiplexed_quant: false
  target_channels: 4,8
  decoy_channel: 12
  reference_channel: 0
  competetive_scoring: true
selection_config:
  peak_len_rt: 10
  sigma_scale_rt: 0.5
  peak_len_mobility: 0.1
  sigma_scale_mobility: 1
  top_k_precursors: 3
  top_k_fragments: 12
  kernel_size: 30
  f_mobility: 1
  f_rt: 0.99
  center_fraction: 0.5
  min_size_mobility: 8
  min_size_rt: 3
  max_size_mobility: 50
  max_size_rt: 15
  group_channels: false
  use_weighted_score: true
  join_close_candidates: true
  join_close_candidates_scan_threshold: 0.01
  join_close_candidates_cycle_threshold: 0.6
