name: PeptideCentric.v1
general:
  thread_count: 10
  reuse_calibration: true
  reuse_quant: false
  astral_ms1: false
  log_level: INFO
library_loading:
  save_hdf: true
search:
  channel_filter: ''
  exclude_shared_ions: true
  target_num_candidates: 5
  target_ms1_tolerance: 15
  target_ms2_tolerance: 15
  target_mobility_tolerance: 0.04
  target_rt_tolerance: 60
fdr:
  fdr: 0.01
  group_level: proteins
  competetive_scoring: true
  channel_wise_fdr: false
  keep_decoys: false
extraction_initial:
  initial_num_candidates: 2
  initial_ms1_tolerance: 30
  initial_ms2_tolerance: 30
  initial_mobility_tolerance: 0.08
  initial_rt_tolerance: 240
multiplexing:
  multiplexed_quant: false
  target_channels: 4,8
  decoy_channel: 12
  reference_channel: 0
  competetive_scoring: true
