
general:
  thread_count: 10
  reuse_calibration: true
  reuse_quant: true
  use_gpu: true
  astral_ms1: false
  log_level: INFO
library_prediction:
  predict: false
  enzyme: trypsin
  fixed_modifications: Carbamidomethyl@C
  missed_cleavages: 2
  precursor_len:
    - 7
    - 35
  precursor_charge:
    - 2
    - 4
  precursor_mz:
    - 400
    - 1200
  fragment_mz:
    - 100
    - 2000
  nce: 25
  instrument: Astral
  save_hdf: true
search:
  channel_filter: ''
  exclude_shared_ions: true
  target_num_candidates: 5
  target_ms1_tolerance: 5
  target_ms2_tolerance: 10
  target_mobility_tolerance: 0.04
  target_rt_tolerance: 300
fdr:
  fdr: 0.01
  group_level: genes
  competetive_scoring: true
  inference_strategy: maximum_parsimony
  channel_wise_fdr: false
  keep_decoys: false
search_initial:
  initial_num_candidates: 2
  initial_ms1_tolerance: 30
  initial_ms2_tolerance: 30
  initial_mobility_tolerance: 0.18
  initial_rt_tolerance: 600
multiplexing:
  multiplexed_quant: false
  target_channels: 4,8
  decoy_channel: 12
  reference_channel: 0
  competetive_scoring: true
