# Default values in case extraction_backend="python"
# Note: make sure to adapt the frontend defaults conditionally once any of these become configurable from the frontend or
# if you add something that is already configurable from the frontend.
calibration:
  batch_size: 8000
  optimization_lock_target: 200
  min_steps: 2
optimization:
  rt_error:
      automatic_update_percentile_range: 0.99
      automatic_update_factor: 1.1
      maximal_decrease: 0.2
      favour_narrower_optimum: True
      maximum_decrease_from_maximum: 0.1
