# configuration for the extraction plan
version: 1

general:
  thread_count: 10
  # maximum number of threads or processes to use per raw file
  reuse_calibration: false
  reuse_quant: false
  astral_ms1: false
  log_level: 'INFO'
  wsl: false
  mmap_detector_events: false
  use_gpu: true

library_loading:
  rt_heuristic: 180
  # if retention times are reported in absolute units, the rt_heuristic defines rt is interpreted as minutes or seconds

library_prediction:
  predict: False
  enzyme: trypsin
  fixed_modifications: 'Carbamidomethyl@C'
  variable_modifications: 'Oxidation@M;Acetyl@Protein N-term'
  max_var_mod_num: 2
  missed_cleavages: 1
  precursor_len:
    - 7
    - 35
  precursor_charge:
    - 2
    - 4
  precursor_mz:
    - 400
    - 1200
  fragment_mz:
    - 200
    - 2000
  nce: 25.0
  # semicolon separated list of fragment types. Supported types are: a, b, c, x, y, z, b_modloss, y_modloss
  fragment_types: 'b;y'
  # maximum charge state for predicted fragments
  max_fragment_charge: 2
  instrument: Lumos
  checkpoint_folder_path: None

search:
  channel_filter: '0'
  exclude_shared_ions: True
  compete_for_fragments: True

  target_num_candidates: 2
  target_ms1_tolerance: 15
  target_ms2_tolerance: 15
  target_mobility_tolerance: 0.04
  target_rt_tolerance: 60

  quant_window: 3
  quant_all: True

search_advanced:
  top_k_fragments: 12

calibration:
  min_epochs: 3
  max_epochs: 20
  batch_size: 8000
  recalibration_target: 200
  final_full_calibration: False
  norm_rt_mode: 'linear'

search_initial:
  initial_num_candidates: 1
  initial_ms1_tolerance: 30
  initial_ms2_tolerance: 30
  initial_mobility_tolerance: 0.08
  initial_rt_tolerance: 240

selection_config:
  peak_len_rt: 10.
  sigma_scale_rt: 0.5
  peak_len_mobility: 0.01
  sigma_scale_mobility: 1.

  top_k_precursors: 3
  kernel_size: 30

  f_mobility: 1.0
  f_rt: 0.99
  center_fraction: 0.5
  min_size_mobility: 8
  min_size_rt: 3
  max_size_mobility: 20
  max_size_rt: 15

  group_channels: False
  use_weighted_score: True

  join_close_candidates: False
  join_close_candidates_scan_threshold: 0.6
  join_close_candidates_cycle_threshold: 0.6

scoring_config:
  score_grouped: false
  top_k_isotopes: 3
  reference_channel: -1
  precursor_mz_tolerance: 10
  fragment_mz_tolerance: 15

multiplexing:
  enabled: False
  target_channels: '4,8'
  decoy_channel: 12
  reference_channel: 0
  competetive_scoring: True

fdr:
  fdr: 0.01
  group_level: 'proteins'
  competetive_scoring: true
  keep_decoys: false
  channel_wise_fdr: false
  inference_strategy: "heuristic"

search_output:
  peptide_level_lfq: false
  precursor_level_lfq: false
  min_k_fragments: 12
  min_correlation: 0.9
  num_samples_quadratic: 50
  min_nonnan: 3
  normalize_lfq: True

# configuration for the optimization manager
# initial parameters, will nbe optimized
optimization_manager:
  fwhm_rt: 5
  fwhm_mobility: 0.01
  score_cutoff: 0

# This section controls transfer learning
# currently only the library is created with transfer learning
transfer_learning:
  # if true, the library is created with transfer learning
  enabled: False

  # semicolon separated list of fragment types to include in the library. possible values are 'a', 'b', 'c', 'x', 'y', 'z'
  fragment_types: 'b;y'

  # maximum charge for fragments
  max_charge: 2

  # If a given precursor appears multiple times in an experiment,
  # only the top_k_samples with the highest scores are included in the library
  top_k_samples: 3

  # (experimental) Perform advanced rt calibration:
  # If set to false retention times will be normalised by the maximum retention time observed in the experiment
  # If set to true, a combination of maximum normalisation and deviation from the calibration curve will be used
  norm_delta_max: true

  # Use only precursors for ms2 training with a median XIC correlation above this threshold
  precursor_correlation_cutoff: 0.5

  # include only fragments with a XIC correlation at least 0.75 of the median for all fragments
  fragment_correlation_ratio: 0.75

# configuration for the calibration manager
# the config has to start with the calibration keyword and consists of a list of calibration groups.
# each group consists of datapoints which have multiple properties.
# This can be for example precursors (mz, rt ...), fragments (mz, ...), quadrupole (transfer_efficiency)
calibration_manager:
  - name: fragment
    estimators:
      - name: mz
        model: LOESSRegression
        model_args:
          n_kernels: 2
        input_columns:
          - mz_library
        target_columns:
          - mz_observed
        output_columns:
          - mz_calibrated
        transform_deviation: 1e6
  - name: precursor
    estimators:
        - name: mz
          model: LOESSRegression
          model_args:
            n_kernels: 2
          input_columns:
            - mz_library
          target_columns:
            - mz_observed
          output_columns:
            - mz_calibrated
          transform_deviation: 1e6
        - name: rt
          model: LOESSRegression
          model_args:
            n_kernels: 6
          input_columns:
            - rt_library
          target_columns:
            - rt_observed
          output_columns:
            - rt_calibrated
        - name: mobility
          model: LOESSRegression
          model_args:
            n_kernels: 2
          input_columns:
            - mobility_library
          target_columns:
            - mobility_observed
          output_columns:
            - mobility_calibrated
