# Create a draft release and build and upload all installers to it.
name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      commit_to_release:
        description: 'Enter commit hash to release (example: ef4037cb571f99cb4919b520fde7174972aae473)'
        type: string
        required: true
      tag_to_release:
        description: 'Enter tag to release (example: v1.5.5)'
        type: string
        required: true

jobs:
  create-release:
    secrets: inherit
    permissions:
      contents: write
      actions: write
    uses: MannLabs/alphashared/.github/workflows/create_release.yml@v1
    with:
      package_name: alphadia
      commit_to_release: ${{ inputs.commit_to_release }}
      tag_to_release: ${{ inputs.tag_to_release }}
      build_nodejs_ui: true
      test_app: true
