on:
  pull_request:
    branches: [ main, development ]  # TODO remove development here
  push:
    branches: [ main, development ]
  workflow_dispatch:

name: end to end testing

env:
#  TEST_DATA_DIR: C:\actions-runner\_data
#  CONDA: C:\Users\wallmann\Miniconda3
  NEPTUNE_TOKEN: ${{ secrets.NEPTUNE_TOKEN }}

jobs:
  end2end_testing:
    name: Test loose pip installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            conda-env-path: "/usr/share/miniconda3/envs/alphadia"
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.conda-env-path }}
          key: ${{ matrix.os }}-conda-${{ hashFiles('**/requirements.txt') }}
        id: cache
      - name: Pip installation with loose dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash -el {0}
        run: |
          cd misc
          . ./loose_pip_install.sh
      - name: Run e2e tests
        shell: bash -el {0}
        run: |
          cd tests
           . ./run_e2e_tests.sh
