on:
  pull_request:
    branches:
  push:
    branches: [ main, development ]
  workflow_dispatch:

name: End to end testing

jobs:
  end2end_testing:
    name: End to end test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: self-hosted
    env:
      RUN_NAME: alphadia-${{github.sha}}-${{github.run_id}}-${{github.run_attempt}}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Pip installation with loose dependencies
        shell: bash -el {0}
        run: |
          cd misc
          . ./loose_pip_install.sh $RUN_NAME
      - name: Run e2e tests
        shell: bash -el {0}
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_E2E_TOKEN }}
          NEPTUNE_PROJECT_NAME: "MannLabs/alphaDIA-e2e-tests"
        run: |
          cd tests
           . ./run_e2e_tests.sh basic_e2e $RUN_NAME ${GITHUB_SHA::7} $BRANCH_NAME
      - name: Cleanup
        if: always()
        shell: bash -el {0}
        run: |
          conda remove -n $RUN_NAME --all
