on:
  push:
    branches:
      - 'development'
  workflow_dispatch:

name: Default installation and tests

jobs:
  loose_installation:
    name: Loose pip installation
    runs-on: AlphaDIA
    env: # Or as an environment variable
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./loose_pip_install.sh
      - name: Unittests
        env: # Or as an environment variable
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
        shell: bash -l {0}
        run: |
          conda activate alphadia
          python tests/performance_tests/fdr_test.py
