on:
  pull_request:
    branches: [ main,  ]  # TODO re-add development
  workflow_dispatch:

name: FDR performance test

jobs:
  loose_installation:
    name: Loose pip installation
    runs-on: AlphaDIA
    env: # Or as an environment variable
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./loose_pip_install.sh
      - name: Run legacy classifier
        env: # Or as an environment variable
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
        shell: bash -l {0}
        run: |
          conda activate alphadia
          python tests/performance_tests/fdr_test.py \
          --classifier legacy_new_batching \
          --threads 4 \
          --neptune-tag github-action \
          --neptune-tag "bracnh:${{ steps.extract_branch.outputs.branch }}"
      - name: Run binary classifier
        env: # Or as an environment variable
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
        shell: bash -l {0}
        run: |
          conda activate alphadia
          python tests/performance_tests/fdr_test.py \
          --classifier binary \
          --threads 4 \
          --neptune-tag github-action \
          --neptune-tag "bracnh:${{ steps.extract_branch.outputs.branch }}"
