on:
  pull_request:
    types: [ labeled ]
  push:
    branches: [ main ]
  workflow_dispatch:

name: FDR performance test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fdr_performance_testing:
    if: contains(github.event.pull_request.labels.*.name, 'test:fdr') || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: FDR performance testing
    runs-on: AlphaDIA
    env: # Or as an environment variable
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Pip installation (stable)
        shell: bash -l {0}
        run: |
          cd misc
          . ./pip_install.sh stable,tests alphadia 3.11 true
      - name: Run legacy_new_batching classifier
        env: # Or as an environment variable
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_FDR_TOKEN }}
        shell: bash -l {0}
        run: |
          conda activate alphadia
          python tests/performance_tests/fdr_test.py \
          --classifier legacy_new_batching \
          --threads 4 \
          --neptune-tag github-action \
          --neptune-tag "branch:${{ steps.extract_branch.outputs.branch }}"
