on:
  pull_request:
    branches: [alpha]
  
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: ../_data/

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Add conda to path
        shell: PowerShell	
        run: |
          $env:PATH += ';C:\Users\wallmann\Miniconda3\bin'
      - name: Conda info
        shell: PowerShell	
        run: |
          $env:GITHUB_PATH
          $env:CONDA
          $env:PATH
          conda info
