on:
  pull_request:
    branches: [alpha]
  
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: ../_data/

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Conda info
        shell: bash -l {0}
        run: conda info
