on:
  pull_request:
    branches: [alpha]
  
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: ../_data/

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-update-conda: true
          python-version: '3.9'
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./loose_pip_install.sh
      - name: Performance tests
        shell: bash -l {0}
        run: |
          cd tests
          . ./run_performance_tests.sh
