on:
  pull_request:
    branches: [alpha]
  
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: ..\_data\
  CONDA: C:\Users\wallmann\Miniconda3

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: alpha
          python-version: '3.9'
      - name: Conda info
        run: |
          conda info
          echo "$PATH"
          echo "$CONDA"
