on:
  pull_request:
    branches: [alpha]
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: ../_data/

jobs:
  stable_installation:
    name: Test stable pip installation on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all stable dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./stable_pip_install.sh
      - name: Unittests
        shell: bash -l {0}
        run: |
          cd tests
          . ./run_perfromance_tests.sh