on:
  pull_request:
    branches:
      - 'alpha'
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: C:\actions-runner\_data
  CONDA: C:\Users\wallmann\Miniconda3
  NEPTUNE_TOKEN: ${{ secrets.NEPTUNE_TOKEN }}

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install alphadia
        run: |
          conda activate alpha
      - name: Diann re extraction
        run: |
            python tests/performance_tests/1_brunner_2022_1ng_all.py
