on:
  pull_request:
    branches: [alpha]
  
  workflow_dispatch:

name: performance testing

env:
  TEST_DATA_DIR: ../_data/
  CONDA: C:\Users\wallmann\Miniconda

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Conda info
        shell: PowerShell	
        run: |
          $env:path
          conda info
