on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

name: Perform installation and run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  run-tests-stable:
    name: Test stable pip installation on 3 OS
    strategy:
      matrix:
        os:  [ubuntu-latest, macos-13, windows-latest]
    uses: ./.github/workflows/_run_tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      install-script: ./pip_install.sh stable,test
      test-script: ./run_unit_tests.sh

  run-tests-loose:
    name: Test loose pip installation on 3 OS
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, windows-latest ]
    uses: ./.github/workflows/_run_tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      install-script: ./pip_install.sh test
      test-script: ./run_unit_tests.sh
