# Perform pip installation (stable, loose) and run tests on all three OS

# For feature branches, we don't test the full matrix (os x [stable, loose]) in order to save time & resources.
# On each push to main, the whole test matrix runs.
# In the (assumed to be rare case) that these full matrix tests fail but the reduced matrix tests passed,
# we will learn about it latest after pushing to main.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

name: Pip install + unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  run-unit-tests-stable:
    name: Test 'stable' on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu-latest, macos-13, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    uses: ./.github/workflows/_run_tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      install-script: ./pip_install.sh stable,tests
      test-script: ./run_unit_tests.sh

  run-unit-tests-loose:
    name: Test 'loose' on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-13, windows-latest ]
        python-version: ["3.10", "3.11", "3.12"]
    uses: ./.github/workflows/_run_tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      install-script: ./pip_install.sh tests
      test-script: ./run_unit_tests.sh
