on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:


name: Release on GitHub

jobs:
  Version_Bumped:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.master_version_bumped.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Master version bumped
        id: master_version_bumped
        shell: bash -l {0}
        run: |
          cd misc
          . ./check_version.sh
          echo "$current_version"
          echo "version=$current_version" >> $GITHUB_OUTPUT
      - name Print version
        shell: bash -l {0}
        run: |
          echo "Version: ${{ steps.master_version_bumped.outputs.version }}"
  Print_Version:
    runs-on: ubuntu-latest
    needs: Version_Bumped
    steps:
      - name: Print version
        shell: bash -l {0}
        run: |
          echo "Version: ${{ needs.Version_Bumped.outputs.version }}"
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"