# Update requirements
name: Update requirements

on:
  workflow_dispatch:

jobs:
  update-requirements:
    uses: MannLabs/alphashared/.github/workflows/update_requirements.yml@v1
    secrets: inherit
    with:
      requirements_file_name: requirements.txt
