# Update requirements
name: Update requirements

on:
  workflow_dispatch:

jobs:
  update-requirements:
    uses: MannLabs/alphashared/.github/workflows/update_requirements.yml@v1
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
